#!/bin/sh

# Function to get the battery percentage and status
get_battery_info() {
    battery_path="/sys/class/power_supply/BAT0"

    if [ -e "$battery_path" ]; then
        battery_percentage=$(cat "$battery_path/capacity")
        charging_status=$(cat "$battery_path/status")
        echo "$battery_percentage% $charging_status"
    else
        echo "PC"
    fi
}

# Run once
battery_info=$(get_battery_info)
echo "$battery_info"
